#!/usr/bin/env bash

set -euo pipefail

function run-script {
  local cmd="yarn $1"
  echo $'\e[95mRunning '"${cmd@Q}"$'\e[m'
  if ! yarn "$1"; then
    echo $'\e[91mCommand '"${cmd@Q}"$' failed, commit aborted.\e[m'
    return 1
  fi
}

function fail {
 echo $'\e[95mRestoring current working directory\e[m'
 git stash pop -q
 exit 1
}

echo $'\e[95mStashing current working directory\e[m'
git stash push --include-untracked --keep-index

run-script format-check || fail
run-script typecheck || fail
run-script lint || fail
run-script test || fail

 echo $'\e[95mRestoring current working directory\e[m'
git stash pop

echo $'\e[95mPre-commit checks completed\e[m'
