#!/bin/bash

set -euo pipefail

function run-script {
  local cmd="yarn $1"
  echo $'\e[95mRunning '"${cmd@Q}"$'\e[m'
  if ! yarn "$1"; then
    echo $'\e[91mCommand '"${cmd@Q}"$' failed, commit aborted.\e[m'
    exit 1
  fi
}

run-script format-check
run-script lint
run-script test

echo $'\e[95mPre-commit checks completed\e[m'
