name: Build nightly

on:
    workflow_run:
        workflows: ["Run all automated checks"]
        branches: ["v2"]
        types: ["completed"]
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow one concurrent deployment
concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    # Single deploy job since we're just deploying
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: true

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 10.13.1
            - name: Use Node.js 18
              uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: "pnpm"
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Fetch Contributors
              run: pnpm --filter hyperschedule-frontend get-contributors ${{ secrets.GITHUB_TOKEN }}
            - name: Build production
              run: pnpm --filter hyperschedule-frontend prod
            - name: Setup Pages
              uses: actions/configure-pages@v5
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: 'frontend/dist'
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
