name: Run all automated checks

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "v2"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we use matrix so we can run those in parallel
        command: ["typecheck", "test", "lint", "format"]
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.13.1
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install libcrypto.so.1.1 for MongoDB
        if: matrix.command == 'test'
        run: |
          wget https://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run ${{matrix.command}}
        run: pnpm ci:${{matrix.command}}
