name: Run all unit tests and lints

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we use matrix so we can run those in parallel
        command: ["test --all", lint, format-check]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run ${{matrix.command}}
        run: yarn ${{matrix.command}}
